name = "cert-project"
type = "javascript"
account_id = "f49b1249-3b0b-46eb-bb78-040b9dff5487"
workers_dev = true
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "certificates"
database_id = "your_d1_database_id_here"

[build]
upload.format = "modules"

[[routes]]
pattern = "*"
type = "pages"
zone_id = "your_zone_id_here"

[site]
bucket = "./public"
entry-point = "functions"